### PR TITLE
added footer and social sites

### PR DESCRIPTION
**Pull request by Abhinav-3359**

### CODE REVIEW

**Comment by jatiinyadav** [comment]
@Abhinav-3359 Thank you for contributing.
Please write CSS in a separate CSS file i.e `main.css`.
And upload a snapshot/screenshot of the UI.

**Comment by Abhinav-3359** [comment]
Okay sir

**Comment by Abhinav-3359** [comment]
vue2

added footer and sites

**Comment by jatiinyadav** [comment]
The `body` class in the `main.css` file is not working

**Comment by Abhinav-3359** [comment]
Okay let me correct it

**Comment by Abhinav-3359** [comment]
sir pls see the new change

**Comment by jatiinyadav** [comment]
@Abhinav-3359 Thank you so much for your contribution. 👍

**Pull request merged**
